### ISSUE TITLE
Just try use readme.md

### ISSUE THREAD

**Issue by alexandrzlobin** [eborghi10/spot_quadruped_ros#10]
When you will publish instructions?) My all five children wait spot micro.

**Comment by eborghi10** [comment]
Hi, this project is not intended for kids since it uses ROS. Maybe you can try the Arduino-based quadruped, see [here](https://spotmicroai.readthedocs.io/en/latest/).

Also, keep in mind that I'm not actively working on this project because of hardware costs and difficulties to buy hardware. Instead, I'm focused on a [simulation of an MIT Mini Cheetah](https://github.com/eborghi10/quadruped_ctrl).
